MVCDolce/Models/Visitas.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MVCDolce.Models
{
    public class Visitas
    {

    }

    public class Pdh
    {
        [Required(ErrorMessage = "El nombre es Requerido")]
        [Display(Name = "Nombre de la Asesora")]
        [RegularExpression("^(?!Aa|Bb|Cc).*$", ErrorMessage = "Para el nombre solo se admiten letras")]
        public string StrNombre { get; set; }

        [Display(Name = "Telefono fijo o Celular")]
        [RegularExpression("^[0-9]*$", ErrorMessage = "Para el Telefono solo se admiten numeros")]
        [StringLength(10, ErrorMessage = "El telefono debe contener maximo 10 caracteres")]
        public string StrTelefono { get; set; }

        [Required(ErrorMessage = "La Observacion es Requerida")]
        [Display(Name = "Observacion")]
        [MinLength(10, ErrorMessage = "Minimo debe de escribir 10 caracteres")]
        public string StrObservacion { get; set; }

        public string StrEmail { get; set; }
    }

    public class PosibleNueva
    {
        public Int64 Id { get; set; }

        [Required(ErrorMessage = "El documento es requerido")]
        [Display(Name = "Documento No")]
        [RegularExpression("^[0-9]*$", ErrorMessage = "En el campo documento solo se admiten numeros")]
        [MinLength(5, ErrorMessage = "La cedula debe de ser minimo de 5 caracteres")]
        public string StrDocumento { get; set; }


        [Required(ErrorMessage = "El Nombre es requerido")]
        [Display(Name = "Nombres")]
        [RegularExpression("^(?!Aa|Bb|Cc).*$", ErrorMessage = "Para el nombre solo se admiten letras")]
        [MinLength(5, ErrorMessage = "El Campo nombre debe de tener minimo 5 caracteres")]
        public string StrNombres { get; set; }

        [Required(ErrorMessage = "El Apellido es requerido")]
        [Display(Name = "Apellidos")]
        [RegularExpression("^(?!Aa|Bb|Cc).*$", ErrorMessage = "Para el apellido solo se admiten letras")]
        [MinLength(5, ErrorMessage = "El Campo apellido debe de tener minimo 5 caracteres")]
        public string StrApellidos { get; set; }

        [Required(ErrorMessage = "La direccion es requerido")]
        [Display(Name = "Direccion")]
        [RegularExpression("^(?!Aa|Bb|Cc).*$", ErrorMessage = "Para la direccion solo se admiten letras")]
        [MinLength(5, ErrorMessage = "El Campo direccion debe de tener minimo 5 caracteres")]
        public string StrDireccion { get; set; }

        [Display(Name = "Telefono fijo")]
        [RegularExpression("^[0-9]*$", ErrorMessage = "En el campo telefono solo se admiten numeros")]
        [MinLength(5, ErrorMessage = "el telefono debe de ser minimo de 5 caracteres")]
        public string StrTelefono { get; set; }


        [Required(ErrorMessage = "El campo celular es requerido")]
        [Display(Name = "Celular")]
        [RegularExpression("^[0-9]*$", ErrorMessage = "En el campo celular solo se admiten numeros")]
        [MinLength(10, ErrorMessage = "el celular debe de ser de 5 caracteres")]
        public string StrCelular { get; set; }


        [Required(ErrorMessage = "El campo departamento es requerido")]
        [Display(Name = "Departamento")]
        public string StrDepartamento { get; set; }

        [Required(ErrorMessage = "El campo ciudad es requerido")]
        [Display(Name = "Ciudad")]
        public string StrCiudad { get; set; }

        [Required(ErrorMessage = "El campo barrio es requerido")]
        [Display(Name = "Poblacion o Barrio")]
        public string StrBarrio { get; set; }

        public string StrImagen { get; set; }
        public string StrEmail { get; set; }

    }


    public class ListaVisitaApoyo
    {
        public Int64 Id { get; set; }
        public string StrDocumento { get; set; }
        public string StrNombre { get; set; }
        public bool LogVisita { get; set; }
    }

    public class Apoyo
    {
        public string StrDocumento { get; set; }
        [Display(Name = "Nombre de la Asesora")]
        public string StrNombre { get; set; }

        [Required(ErrorMessage = "El campo Observacion es requerido")]
        [Display(Name = "Observacion")]
        public string StrObservacion { get; set; }

        [Display(Name = "Tiene Pedido")]
        public string StrPedido { get; set; }

        public bool LogPedido { get; set; }

        public string StrEmail { get; set; }

    }

    public class Nuevas
    {
        public string StrEmail { get; set; }
        [Display(Name = "Documento No")]
        public string StrDocumento { get; set; }

        [Display(Name = "Nombre de la Asesora")]
        public string StrNombre { get; set; }


        public Int32 NumPuntos { get; set; }
        public double CurValorPedido { get; set; }

        [Display(Name = "Observacion")]
        public string StrObservacion { get; set; }

        public string StrTelefono { get; set; }


    }

    public class ListaCobranza
    {
        public string StrEmail { get; set; }
        public string StrCampaña { get; set; }
        public string StrDocumento { get; set; }
        public string StrNombre { get; set; }
        public double CurSaldo { get; set; }
        public string DtmFechaVencimiento { get; set; }
        public Int32 NumPuntos { get; set; }
        public string StrTelefono { get; set; }
        public string StrObservacion { get; set; }


    }

    public class Motivacion
    {
        public string StrEmail { get; set; }
        public string StrZona { get; set; }
        public string StrDocumento { get; set; }
        public string StrNombre { get; set; }
        public string StrTelefono { get; set; }
        public Int32 NumPuntos { get; set; }
        public string StrUltimaCampaña { get; set; }
        public string StrObservacion { get; set; }
        public string  StrTipoAsesora { get; set; }

    }

    public class PosiblesReingresos
    {
        public string StrEmail { get; set; }
        public string StrDocumento { get; set; }
        public string StrNombre { get; set; }
        public string StrTelefono { get; set; }
        public string StrUltimaCampaña { get; set; }
        public string StrObservacion { get; set; }

        public double CurSaldo { get; set; }


    }

    public class InformeVisitas
    {
        public string StrCampaña { get; set; }
        public string StrDivision { get; set; }
        public string StrZona { get; set; }
        public string StrDocumento { get; set; }
        public string StrNombre { get; set; }
        public int IdTipoVisita { get; set; }
        public string StrTipoVisita { get; set; }
        public string StrObservacion { get; set; }
        public string LogPedido { get; set; }
        public string DtmFecha { get; set; }
        public string DtmHora { get; set; }
    }

    public class InformeVisitasDiv
    {
        public string StrCampaña { get; set; }
        public string StrEmail { get; set; }
        public string StrZona { get; set; }

    }
}

MVCDolce/Controllers/VisitasController.cs
using MVCDolce.Clases;
using MVCDolce.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;

namespace MVCDolce.Controllers
{
    public class VisitasController : Controller
    {
        // GET: Visitas
        private string _strMensaje;

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult MenuDivisional()
        {
            return View();
        }

        public ActionResult Pdh()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Pdh(Pdh modelo)
        {

            if (ModelState.IsValid)
            {
                var vc = new Clases.VisitasDao();

                var usuario = Session["Usuario"].ToString();

                modelo.StrEmail = usuario;


                var res = vc.AddPdh(modelo, out _strMensaje);

                if (res)
                {
                    ViewBag.mensaje = _strMensaje;
                    return View();
                }
                else
                {
                    ViewBag.Error = _strMensaje;
                    return View();
                }
            }
            else
            {
                ViewBag.Error = "Los datos no estan completos";
                return View();
            }

        }

        public ActionResult PosibleNueva()
        {
            return View();
        }

        [HttpPost]
        public ActionResult PosibleNueva(PosibleNueva modelo)
        {
            if (ModelState.IsValid)
            {
                var vc = new Clases.VisitasDao();

                var usuario = Session["Usuario"].ToString();

                modelo.StrEmail = usuario;

                var res = vc.AddPosibleNueva(modelo, out _strMensaje);

                if (res)
                {
                    ViewBag.mensaje = _strMensaje;
                    return View();
                }
                else
                {
                    ViewBag.Error = _strMensaje;
                    return View();
                }
            }
            else
            {
                ViewBag.Error = "Los datos no estan completos";
                return View();
            }
        }

        public ActionResult ListadoApoyo()
        {
            var vc =new Clases.VisitasDao();

            var usuario = Session["Usuario"].ToString();

            var lista = vc.ListadoVisitadeApoyo(usuario, out _strMensaje);

            if (lista != null)
            {
                ViewData["ListaApoyo"] = lista;
              
            }
            else
            {
                ViewBag.Error = _strMensaje;
            }      

            return View();
        }

        public ActionResult Apoyo(string strCedula,string strNombre)
        {
            ViewBag.nombre = strNombre;
            ViewBag.cedula = strCedula;

            return View();
        }
        [HttpPost]
        public ActionResult Apoyo(Apoyo modelo)
        {
          
            
            var vc = new Clases.VisitasDao();

            bool pedido = false;

            if (modelo.StrPedido != null)
            {
                pedido = true;
            }



            var usuario = Session["Usuario"].ToString();

            modelo.StrEmail = usuario;
            modelo.LogPedido = pedido;

            var res = vc.AddApoyo(modelo, out _strMensaje);

            if (res)
            {
                ViewBag.mensaje = _strMensaje;

            }
            else
            {
                ViewBag.Error = _strMensaje;
            }

            


            return View();
        }

        public ActionResult ListadoNuevas()
        {

            var usuario = Session["Usuario"].ToString();

            var vc = new Clases.VisitasDao();

            var datos = vc.ConsultaNuevas(usuario, out _strMensaje);

            if (datos != null)
            {
                ViewData["ListaNuevas"] = datos;
            }
            else
            {
                ViewBag.Error = _strMensaje;
            }

            return View();
        }

        public ActionResult Nuevas(string strCedula)
        {

            var usuario = Session["Usuario"].ToString();
            var vc = new Clases.VisitasDao();

            var datos = vc.ConsultaNueva(usuario, strCedula, out _strMensaje);

            ViewBag.cedula = strCedula;
            ViewBag.nombre = datos.StrNombre;
            ViewBag.valor = datos.CurValorPedido;
            ViewBag.puntos = datos.NumPuntos;

            return View();
        }

        [HttpPost]
        public ActionResult Nuevas(Nuevas modelo)
        {
            var usuario = Session["Usuario"].ToString();

            modelo.StrEmail = usuario;

            var vc = new Clases.VisitasDao();

            var res = vc.AddNueva(modelo, out _strMensaje);

            if (res)
            {
                ViewBag.mensaje = _strMensaje;
                
            }
            else
            {
                ViewBag.Error = _strMensaje;
                
            }

            return View();


        }

        public ActionResult ListadoCobranza(int? page, string consulta="")
        {
            var usuario = Session["Usuario"].ToString();

            var vc = new Clases.VisitasDao();

            var xlista = vc.ListadoCobranza(usuario, out _strMensaje);


            if (consulta != "")
            {
                if (xlista != null)
                {
                    var xfiltro = xlista.Where(x => x.StrDocumento.Contains(consulta)).ToList();

                    if (xfiltro.Count > 0)
                    {

                        var pageNumber = page ?? 1;
                        var cobranza = xfiltro.ToPagedList(pageNumber, 10);

                        ViewBag.cobranza = cobranza;
                        ViewBag.conteo = xfiltro.Count;

                    }
                    else
                    {
                        var pageNumber = page ?? 1;
                        var cobranza = xlista.ToPagedList(pageNumber, 10);


                        ViewBag.cobranza = cobranza;
                        ViewBag.conteo = xlista.Count;

                    }
                }
                else
                {
                    ViewBag.Error = _strMensaje;
                }
            }
            else
            {
                if (xlista != null)
                {
                    var pageNumber = page ?? 1;

                    var cobranza = xlista.ToPagedList(pageNumber, 10);

                    ViewBag.cobranza = cobranza;
                    ViewBag.conteo = xlista.Count;
                }
                else
                {
                    ViewBag.Error = _strMensaje;
                }
            }



            return View();

        }

        public ActionResult Cobranza(string strCedula,string strNombre,double curSaldo,string campana,Int32 puntos)
        {

            ViewBag.cedula = strCedula;
            ViewBag.nombre = strNombre;
            ViewBag.saldo = curSaldo;
            ViewBag.campana = campana;
            ViewBag.puntos = puntos;

            return View();


        }

        [HttpPost]
        public ActionResult Cobranza(ListaCobranza modelo)
        {

            ViewBag.cedula = modelo.StrDocumento;
            ViewBag.nombre = modelo.StrNombre;
            ViewBag.saldo = modelo.CurSaldo;
            ViewBag.campana = modelo.StrCampaña;
            ViewBag.puntos = modelo.NumPuntos;

            var usuario = Session["Usuario"].ToString();

            modelo.StrEmail = usuario;

            var vc = new Clases.VisitasDao();

            var res = vc.AddCobranza(modelo, out _strMensaje);

            if (res)
            {
                ViewBag.mensaje = _strMensaje;
                //return RedirectToAction("Index", "Visitas");
            }
            else
            {
                ViewBag.Error = _strMensaje;
               
            }

             return View();

        }

        public ActionResult ListaMotivacion(int? page,string consulta="")
        {

            var usuario = Session["Usuario"].ToString();

            var vc = new Clases.VisitasDao();

            var datos = vc.ListadoMotivacion(usuario, out _strMensaje);

            if (consulta != "")
            {
                if (datos != null)
                {
                    var xfiltro = datos.Where(x => x.StrDocumento.Contains(consulta)).ToList();

                    if (xfiltro.Count > 0)
                    {
                        var pageNumber = page ?? 1;
                        var motivacion = xfiltro.ToPagedList(pageNumber, 10);

                        ViewBag.motivacion = motivacion;
                        ViewBag.conteo = xfiltro.Count;
                    }
                    else
                    {
                        var pageNumber = page ?? 1;
                        var motivacion = datos.ToPagedList(pageNumber, 10);

                        ViewBag.motivacion = motivacion;
                        ViewBag.conteo = datos.Count;
                    }

                }
                else
                {
                    ViewBag.Error = _strMensaje;
                }
            }
            else
            {
                if (datos != null)
                {
                    var pageNumber = page ?? 1;
                    var motivacion = datos.ToPagedList(pageNumber, 10);

                    ViewBag.motivacion = motivacion;
                    ViewBag.conteo = datos.Count;

                }
                else
                {
                    ViewBag.Error = _strMensaje;
                   
                }
            }


            return View();

        }

        public ActionResult Motivacion(string cedula)
        {
            ViewBag.cedula = cedula;
            return View();
        }

MVCDolce/Views/Visitas/ListaMotivacion.cshtml
@model MVCDolce.Models.Motivacion
@{
    ViewBag.Title = "Lista de Motivacion";

    //var xlista = ViewData["ListaMotivacion"] as List<MVCDolce.Models.Motivacion>;

    //var total = (xlista == null) ? 0 : xlista.Count;

    var mensaje = (ViewBag.mensaje == null) ? string.Empty : ViewBag.mensaje;
    var error = (ViewBag.Error == null) ? string.Empty : ViewBag.Error;
}

@using PagedList.Mvc;
@using PagedList;


@Html.Hidden("mensaje", (object)mensaje)
@Html.Hidden("Mensaje_error", (object)error)
@Html.Hidden("urlConsulta",Url.Action("ListaMotivacion","Visitas"))

<div class="container">

    <div class="div-search row">
        <h3>Consulta</h3>
        <div class="div-search-input input-field col m6 s10">
            <input type="text" id="txt-consulta" />
            <label for="txt-consulta">Documento</label>
        </div>
        <div class="div-search-buttom col m1 s1">
            <a class="btn-floating btn-large waves-effect waves-light red" onclick="buscar()"><i class="material-icons">search</i></a>
        </div>
    </div>

    <table class="striped">
        <thead>
            <tr>
                <th data-field="avatar">Avatar</th>
                <th data-field="id">Documento</th>
                <th data-field="name">Nombre de la Asesora</th>
                <th data-field="telfono">Telefono</th>
                <th data-field="puntos">Puntos Activos</th>
                <th data-field="campana">Ultima Campaña</th>
                <th data-field="tipo">Tipo de Asesora</th>
                <th data-field="price">Seleccionar</th>
            </tr>
        </thead>

        <tbody>


            @if (ViewBag.motivacion != null)
            {
                foreach (var item in ViewBag.motivacion)
                {


                    <tr>
                        <td style="text-align:center"><i class="material-icons">account_circle</i></td>
                        <td>@item.StrDocumento</td>
                        <td>@item.StrNombre</td>
                        <td>@item.StrTelefono </td>
                        <td>@item.NumPuntos </td>
                        <td>@item.StrUltimaCampaña </td>
                        <td>@item.StrTipoAsesora</td>
                        <td style="text-align:center"><a href="~/Visitas/Motivacion?cedula=@item.StrDocumento"><i class="material-icons">grade</i></a></td>
                    </tr>
                }
            }

        </tbody>
    </table>

    <div class="section">
        <h3>Total de Asesoras <span>@ViewBag.conteo</span></h3>
    </div>

    @if (ViewBag.motivacion != null)
    {
        <div class="row">
            <div class="col s12">
                @Html.PagedListPager((IPagedList)ViewBag.motivacion, page => Url.Action("ListaMotivacion", new { page }))
            </div>
        </div>
    }

</div>

@section scripts
    {
        
        <script src="~/Scripts/Visitas.js"></script>

        <script type="text/javascript">
            $(function () {
            });

            function buscar() {

                var txtconsulta = $("#txt-consulta").val();

                var url = $("#urlConsulta").val();
                if (txtconsulta != "") {
                    window.location.href = url + '?consulta=' + txtconsulta;
                } else {
                    window.location.href = url;
                }
            }

        </script>

    }

MVCDolce/Views/Visitas/ListadoCobranza.cshtml
@model MVCDolce.Models.ListaCobranza
@{
    ViewBag.Title = "Listado de Cobranza";

    var xlista = ViewBag.cobranza as List<MVCDolce.Models.ListaCobranza>;
    var total = (xlista == null) ? 0 : xlista.Count;

    var mensaje = (ViewBag.mensaje == null) ? string.Empty : ViewBag.mensaje;
    var error = (ViewBag.Error == null) ? string.Empty : ViewBag.Error;

}

@using PagedList.Mvc;
@using PagedList;

@Html.Hidden("mensaje", (object)mensaje)
@Html.Hidden("Mensaje_error", (object)error)
@Html.Hidden("urlConsulta",Url.Action("ListadoCobranza","Visitas"))


<div class="container">

    <div class="div-search row">
        <h3>Consulta</h3>
        <div class="div-search-input input-field col m6 s10">
            <input type="text" id="txt-consulta" />
            <label for="txt-consulta">Documento</label>
        </div>
        <div class="div-search-buttom col m1 s1">
            <a class="btn-floating btn-large waves-effect waves-light red" onclick="buscar()"><i class="material-icons">search</i></a>
        </div>
    </div>

    <table class="striped">
        <thead>
            <tr>
                <th data-field="avatar">Avatar</th>
                <th data-field="id">Documento</th>
                <th data-field="name">Nombre de la Asesora</th>
                <th data-field="telefono">Telefono</th>
                <th data-field="campana">Campaña</th>
                <th data-field="saldo">Saldo pendiente</th>
                <th data-field="price">Seleccionar</th>
            </tr>
        </thead>

        <tbody>


            @if (ViewBag.cobranza != null)
            {
                foreach (var item in ViewBag.cobranza)
                {
                    <tr>
                        <td style="text-align:center"><i class="material-icons">account_circle</i></td>
                        <td>@item.StrDocumento</td>
                        <td>@item.StrNombre</td>
                        <td>@item.StrTelefono</td>
                        <td>@item.StrCampaña</td>
                        <td>$ @string.Format("{0:n0}",item.CurSaldo)</td>
                        <td style="text-align:center"><a href="~/Visitas/Cobranza?strCedula=@item.StrDocumento&strNombre=@item.StrNombre&curSaldo=@item.CurSaldo&campana=@item.StrCampaña&puntos=@item.NumPuntos"><i class="material-icons">grade</i></a></td>
                    </tr>
                }
            }

        </tbody>
    </table>

    <div class="section">
        <h3>Total de Asesoras <span>@ViewBag.conteo</span></h3>
    </div>
    @if (ViewBag.cobranza != null)
    {
        <div class="row">
            <div class="col s12">
                @Html.PagedListPager((IPagedList)ViewBag.cobranza, page => Url.Action("ListadoCobranza", new { page }))
            </div>
        </div>
    }


</div>

@section scripts
    {
       <script src="~/Scripts/Visitas.js"></script>

        <script type="text/javascript">
            $(function () {
            });

            function buscar() {

                var txtconsulta = $("#txt-consulta").val();

                var url = $("#urlConsulta").val();
                if (txtconsulta != "") {
                    window.location.href = url + '?consulta=' + txtconsulta;
                } else {
                    window.location.href = url;
                }

            }

        </script>
    }

MVCDolce/Views/Visitas/ListadoPosiblesReingresosConSaldo.cshtml
@model MVCDolce.Models.PosiblesReingresos
@{
    ViewBag.Title = "Listado de Posibles Reingresos";

    //var xlista = ViewData["ListaPosibles"] as List<MVCDolce.Models.PosiblesReingresos>;

    //var total = (xlista == null) ? 0 : xlista.Count;

    var mensaje = (ViewBag.mensaje == null) ? string.Empty : ViewBag.mensaje;
    var error = (ViewBag.Error == null) ? string.Empty : ViewBag.Error;
}

@using PagedList.Mvc;
@using PagedList;

@Html.Hidden("mensaje", (object)mensaje)
@Html.Hidden("Mensaje_error", (object)error)

@Html.Hidden("urlconsulta", Url.Action("ListadoPosiblesReingresosConSaldo", "Visitas"))

<div class="container">
    <div class="div-search row">
        <h3>Consulta</h3>
        <div class="div-search-input input-field col m6 s10">
            <input type="text" id="txt-consulta" />
            <label for="txt-consulta">Documento</label>
        </div>
        <div class="div-search-buttom col m1 s1">
            <a class="btn-floating btn-large waves-effect waves-light red" onclick="buscar()"><i class="material-icons">search</i></a>
        </div>
    </div>
    <table class="striped">
        <thead>
            <tr>
                <th data-field="avatar">Avatar</th>
                <th data-field="id">Documento</th>
                <th data-field="name">Nombre de la Asesora</th>
                <th data-field="telefono">Telefono</th>
                <th data-field="campana">Ultima Campaña</th>
                <th data-field="saldo">Saldo</th>
                <th data-field="price">Seleccionar</th>
            </tr>
        </thead>

        <tbody>


            @if (ViewBag.reingresos != null)
            {
                foreach (var item in ViewBag.reingresos)
                {
                    <tr>
                        <td style="text-align:center"><i class="material-icons">account_circle</i></td>
                        <td>@item.StrDocumento</td>
                        <td>@item.StrNombre</td>
                        <td>@item.StrTelefono</td>
                        <td>@item.StrUltimaCampaña</td>
                        <td>@string.Format("{0:c}", item.CurSaldo)</td>
                        <td style="text-align:center"><a href="~/Visitas/PosibleReingreso?strCedula=@item.StrDocumento&strNombre=@item.StrNombre&campana=@item.StrUltimaCampaña"><i class="material-icons">grade</i></a></td>
                    </tr>
                }
            }

        </tbody>
    </table>

    <div class="section">
        <h3>Total de Asesoras <span>@ViewBag.conteo</span></h3>
    </div>

    @if (ViewBag.reingresos != null)
    {
        <div class="row">
            <div class="col s12">
                @Html.PagedListPager((IPagedList)ViewBag.reingresos, page => Url.Action("ListadoPosiblesReingresosConSaldo", new { page }))
            </div>
        </div>
    }

</div>
@section scripts
    {
    <script type="text/javascript">

            var filtro = 0;
            $(function () {
            });

            function buscar() {

                var txtconsulta = $("#txt-consulta").val();

                var url = $("#urlconsulta").val();
                if (txtconsulta != "")
                {
                    window.location.href = url + '?consulta=' + txtconsulta;
                } else {
                    window.location.href = url;
                }

            }

            function ConSaldo() {

                filtro = 1;
                var url = $("#urlconsulta").val();


                window.location.href = url + '?filtro_saldo=' + filtro;

            }
    </script>
}

MVCDolce/Views/Visitas/MenuDivisional.cshtml
@{
    ViewBag.Title = "Menu Principal";
}

@section css
    {
        
        <link href="~/Content/visitas.css" rel="stylesheet" />
    }

<div class="container">
    <h2>Menu Principal</h2>
    <div class="divider"></div>

    <ul class="ul-menu-divisional">
        <li class="ul-menu-divisional-li"><a href="~/Visitas/InformeVisitasDivisional">Informe de Visitas<i class="material-icons">description</i></a></li>
    </ul>

</div>

MVCDolce/Views/Visitas/Motivacion.cshtml
@model MVCDolce.Models.Motivacion
@{
    ViewBag.Title = "Motivacion";

    var mensaje = (ViewBag.mensaje == null) ? string.Empty : ViewBag.mensaje;
    var error = (ViewBag.Error == null) ? string.Empty : ViewBag.Error;
}

@Html.Hidden("mensaje", (object)mensaje)
@Html.Hidden("Mensaje_error", (object)error)

@Html.Hidden("urlConsulta", Url.Action("ConsultaAsesoraMotivacion","Visitas"))

<div class="container">
    <form action="~/Visitas/Motivacion" method="post">
        <h2>Motivación</h2>
        <div class="section">
            <div class="input-field col s12">
                <input id="txt-cedula" type="text" class="validate" name="StrDocumento" value="@ViewBag.cedula" />
                <label for="txt-cedula">Documento No</label>
            </div>
        </div>

        <div class="section">
            <div class="input-field col s12">

                @Html.TextBoxFor( x => x.StrNombre, new { @readonly="readonly",@Value = "Nombre Asesora"})
                <label for="txt-nombre">Nombre de la asesora</label>

            </div>
        </div>

        <div class="section">
            <div class="input-field col s12">
                <input id="txt-puntos" type="text" readonly="readonly"  name="NumPuntos" value="0"/>
                <label for="txt-puntos">Puntos Acumulados</label>
            </div>
        </div>

        <div class="section">
            <div class="input-field col s12">
                <input id="txt-ultimacampana" type="text" readonly="readonly" name="StrUltimaCampaña" value="00000" />
                <label for="txt-ultimacampana">Ultima Campaña</label>
            </div>
        </div>

        <div class="section">
            <div class="input-field col s12">
                <input id="txt-observacion" type="text" class="validate" name="StrObservacion" />
                <label for="txt-observacion">Observacion</label>
            </div>
        </div>

        <div class="section">
            <button id="btn-addvisita" type="submit" class="btn-add btn-floating btn-large waves-effect waves-light red"><i class="material-icons">add</i></button>
        </div>


    </form>
</div>

@section scripts
    {
        
        <script src="~/Scripts/Visitas.js"></script>
        <script type="text/javascript">

            $(function () {

                var url = $("#urlConsulta").val();
                var documento = $("#txt-cedula").val();

                if (documento.length > 0)
                {
                    $.ajax({
                        url: url,
                        data: { strDocumento: documento },
                        type: "POST"
                    }).done(function (res) {

                        if (res.Error != undefined) {
                            Materialize.toast(res.Error, 4000);
                        }
                        else {
                            $("#txt-puntos").val(res.datos.NumPuntos);
                            $("#StrNombre").val(res.datos.StrNombre);
                            $("#txt-ultimacampana").val(res.datos.StrUltimaCampaña);
                        }


                    }).fail(function (error) {
                        alert(error.error);
                    });
                }



            });

        </script>
    }